name: Code checkout

on:
  workflow_call:

jobs:

  scan: 
    name: checkout
    runs-on: ubuntu-latest

    steps:

    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Set up JQ
      run: sudo apt-get install -y jq
    
    - name: Checkout repository
      run: |
        git config --global init.defaultBranch main
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git fetch origin ${{ github.ref }}
        git checkout -b ${{ github.ref }} FETCH_HEAD
        
    - name: List files
      run: ls -la