name: 'ECR Push'

on:
  workflow_call:
    inputs:
      jdk_version:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      image_tag: 
        required: true
        type: string
      aws_region:
        required: true
        type: string
      authToken:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string
    secrets:
      ACTIONS_ID_TOKEN_REQUEST_TOKEN:
        required: true

jobs:

  ecr-push:
    name: ECR 
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      run: |
        sudo apt-get update
        sudo apt-get openjdk-${{ inputs.jdk_version }}-jdk
        echo "Check for JDK version:" | java -version

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS CLI
      run: |
        aws configure set region ${{ inputs.aws_region }}
      shell: bash

    - name: Assume Role with GitHub OIDC
      id: assume-role
      run: |
        ROLE=$(aws sts assume-role-with-web-identity --role-arn ${{ inputs.role_to_assume }} --role-session-name GitHubActions --web-identity-token ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }} --duration-seconds 3600)
        echo "AWS_SESSION_TOKEN=$(echo $ROLE | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.ecr_repository }}

    - name: Authenticate do Github Packages
      run: |
        echo "" > .npmrc
        echo "@waycarbon:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_${{ inputs.authToken }}" >> .npmrc

    - name: Build Docker Image
      run: |
        docker build -t ${{ inputs.ecr_repository }}:${{ inputs.image_tag }} .

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ inputs.ecr_repository }}:${{ inputs.image_tag }}