name: 'Security Scan'

on:
  workflow_call:

jobs:

  scan: 
    name: gitleaks
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gitleaks
      run: |
        sudo apt-get update
        curl -s https://raw.githubusercontent.com/gitleaks/gitleaks/main/scripts/install.sh | bash

    - name: Run gitleaks
      run: |
        echo "Run Gitleaks and generate a JSON report"
        gitleaks detect --source ${{github.workspace}} --report-format json --report-path gitleaks-report.json
        echo "Gitleaks scan completed. Report saved as gitleaks-report.json"

    - name: Upload gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json