name: Terraform Apply

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tf_version:
        description: "Version of terraform to install"
        required: true
        type: string
      cloud_provider:
        description: "Cloud provider to use (aws or digitalocean)"
        required: true
        type: string
    secrets:
      # AWS
      AWS_ASSUME_ROLE:
        required: false
      AWS_REGION:
        required: false
      AWS_BUCKET_NAME:
        required: false
      AWS_BUCKET_KEY:
        required: false
      S3_LOCK:
        required: false

      # DigitalOcean
      DO_API_TOKEN:
        required: false
      NEWRELIC_ACCOUNT:
        required: false
      NEWRELIC_API:
        required: false
      NEWRELIC_REGION:
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Set up branch
      run:
        git config --global init.defaultBranch main

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        echo "tvenf location $(which tfenv)"
        echo "tfenv version $(tfenv --version)"

    - name: Set up terraform
      run: |
        tfenv install ${{ inputs.tf_version }}
        tfenv use ${{ inputs.tf_version }}
        tfVersion=$(terraform version)
        echo "terraform version: $tfVersion"

    - name: Configure AWS credentials
      id: configure_aws_credentials
      env:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-assume-role: ${{ secrets.AWS_ASSUME_ROLE }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.aws-assume-role }}
        aws-region: ${{ env.aws-region }}

    - name: Terraform Init (AWS)
      if: ${{ inputs.cloud_provider == 'aws' && github.ref == 'refs/heads/main' }}
      env:
        aws-region: ${{ secrets.AWS_REGION }}
        aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
        aws_bucket_key: ${{ secrets.AWS_BUCKET_KEY }}
        s3_locking: ${{ secrets.S3_LOCK }}
      run: |
        terraform init -backend=true \
          -backend-config="bucket=${aws_bucket_name}" \
          -backend-config="key=${aws_bucket_key}" \
          -backend-config="use_lockfile=${s3_locking}" \
          -backend-config="encrypt=true"
      continue-on-error: false

    - name: Terraform Init (DigitalOcean)
      if: ${{ inputs.cloud_provider == 'digitalocean' && github.ref == 'refs/heads/main' }}
      env:
        aws_region: ${{ secrets.AWS_REGION }}
        aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
        aws_bucket_key: ${{ secrets.AWS_BUCKET_KEY }}
        s3_locking: ${{ secrets.S3_LOCK }}
        TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
        TF_VAR_newrelic_account: ${{ secrets.NEWRELIC_ACCOUNT }}
        TF_VAR_newrelic_api: ${{ secrets.NEWRELIC_API }}
        TF_VAR_newrelic_region: ${{ secrets.NEWRELIC_REGION }}
      run: |
        terraform init -backend=true \
          -backend-config="bucket=${aws_bucket_name}" \
          -backend-config="key=${aws_bucket_key}" \
          -backend-config="use_lockfile=${s3_locking}" \
          -backend-config="region=${aws-region}" \
          -backend-config="encrypt=true"

    - name: Terraform Plan
      if: github.ref == 'refs/heads/main'
      id: plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
        TF_VAR_newrelic_account: ${{ secrets.NEWRELIC_ACCOUNT }}
        TF_VAR_newrelic_api: ${{ secrets.NEWRELIC_API }}
        TF_VAR_newrelic_region: ${{ secrets.NEWRELIC_REGION }}
      run: terraform plan -input=false
      continue-on-error: false

    - name: Terraform Apply
      id: apply
      run: |
        echo deploying
        terraform apply -auto-approve plan
      continue-on-error: false
