name: Terraform Destroy

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tf_version:
        description: "Version of terraform to install"
        required: true
        type: string
    secrets:
      #access_role:
      #  required: true
      #  type: string
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true
      aws_bucket_name:
        required: true
      aws_bucket_key:
        required: true
      aws_dynamodb_table:
        required: true
env:
  aws_region: ${{ secrets.AWS_REGION }}
  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-22-04
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        echo "tvenf location $(which tfenv)"
        echo "tfenv version $(tfenv --version)"

    - name: Setup terraform
      run: |
        tfenv install ${{ inputs.tf_version }}
        tfenv use ${{ inputs.tf_version }}
        echo "Terraform version $(terraform version)"

    - name: Run 'terraform init'
      env:
        aws_region: ${{ secrets.AWS_REGION }}
        aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }} 
        aws_bucket_key: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        aws_dynamodb_table: ${{ secrets.AWS_DYNAMODB_TABLE }}
      run: |
        terraform init -backend=true \
          -backend-config="bucket=${aws_bucket_name}" \
          -backend-config="key=${aws_bucket_key}" \
          -backend-config="dynamodb_table=${aws_dynamodb_table}" \
          -backend-config="region=${aws_region}" \
          -backend-config="encrypt=true"
      if: github.ref == 'refs/heads/main'
      continue-on-error: false

    - name: Terraform Destroy 
      if: github.ref == 'refs/heads/main'
      run: terraform destroy -auto-approve
      continue-on-error: false
