name: Terraform Destroy

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tf_version:
        description: "Version of terraform to install"
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true
      AWS_REGION:
        required: true
      AWS_BUCKET_NAME:
        required: true
      AWS_BUCKET_KEY:
        required: true
      S3_LOCK:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        echo "tvenf location $(which tfenv)"
        echo "tfenv version $(tfenv --version)"

    - name: Setup terraform
      run: |
        tfenv install ${{ inputs.tf_version }}
        tfenv use ${{ inputs.tf_version }}
        echo "Terraform version $(terraform version)"

    - name: Configure AWS credentials 
      id: configure_aws_credentials 
      env:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-assume-role: ${{ secrets.AWS_ASSUME_ROLE }}
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: ${{ env.aws-assume-role }}
        aws-region: ${{ env.aws-region }}

    - name: Run "terraform init"
      env:
        aws-region: ${{ secrets.AWS_REGION }}
        aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }} 
        aws_bucket_key: ${{ secrets.AWS_BUCKET_KEY }}
        s3_locking: ${{ secrets.S3_LOCK }}
      run: |
        terraform init -backend=true \
          -backend-config="bucket=${aws_bucket_name}" \
          -backend-config="key=${aws_bucket_key}" \
          -backend-config="use_lockfile=${s3_locking}" \
          -backend-config="region=${aws_region}" \
          -backend-config="encrypt=true"
      if: github.ref == 'refs/heads/main'
      continue-on-error: false

    - name: Run "terraform destroy"
      if: github.ref == 'refs/heads/main'
      run: terraform destroy -auto-approve
      continue-on-error: false
