name: 'Terraform Lint'

on:
  workflow_call:
    inputs:
      tfversion:
        required: true
        type: string

jobs:
  ci:
    name: integration
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies 
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Set up tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        which tfenv

    - name: Setup terraform
      run: |
        tfenv install ${{ inputs.tfversion }}
        tfenv use ${{ inputs.tfversion }}
        terraform version

    - name: Terraform - Lint and Validate
      run: terraform version
    
    - name: init
      run: terraform init -backend=false

    - name: validate
      run: terraform validate

    - name: check format / lint
      run: terraform fmt -check
      continue-on-error: true