name: 'Terraform Lint'

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tfversion:
        description: "Version of terraform to install"
        required: true
        type: string

jobs:
  ci:
    name: integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        which tfenv

    - name: Setup terraform
      run: |
        tfenv install ${{ inputs.tfversion }}
        tfenv use ${{ inputs.tfversion }}
        terraform version

    - name: Terraform - Lint and Validate
      run: terraform version
    
    - name: init
      run: terraform init -backend=false

    - name: validate
      run: terraform validate

    - name: check format / lint
      run: terraform fmt -check
      continue-on-error: true