name: Terraform Plan

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tf_version:
        description: "Version of terraform to install"
        required: true
        type: string
    secrets:
      ASSUME_ROLE:
        required: true
      AWS_REGION:
        required: true
      AWS_BUCKET_NAME:
        required: true
      AWS_BUCKET_KEY:
        required: true
      AWS_DYNAMODB_TABLE:
        required: true

env:
  assume_role: ${{ secrets.ASSUME_ROLE }}
  aws_region: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Checkout repository
      uses: ./.github/workflows/checkout.yaml

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        echo "tvenf location $(which tfenv)"
        echo "tfenv version $(tfenv --version)"

    - name: Setup terraform
      run: |
        tfenv install ${{ inputs.tf_version }}
        tfenv use ${{ inputs.tf_version }}
        echo "Terraform version $(terraform version)"

    - name: Configure AWS credentials 
      id: configure_aws_credentials 
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: ${{ env.assume_role }}
        role-session-name: github-actions-federation
        aws-region: ${{ env.aws_region }}

    - name: terraform init
      id: init
      env:
        aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }} 
        aws_bucket_key: ${{ secrets.AWS_BUCKET_KEY }}
        aws_dynamodb_table: ${{ secrets.AWS_DYNAMODB_TABLE }}
      run: |
        terraform init -backend=true \
          -backend-config="bucket=${aws_bucket_name}" \
          -backend-config="key=${aws_bucket_key}" \
          -backend-config="dynamodb_table=${aws_dynamodb_table}" \
          -backend-config="region=${aws_region}" \
          -backend-config="encrypt=true"
      if: github.ref == 'refs/heads/main'
      continue-on-error: false

    - name: terraform plan
      id: plan
      run: terraform plan -input=false
      if: github.ref == 'refs/heads/main'
      continue-on-error: false